# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flashcardWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FlashcardWindow(object):
    def setupUi(self, FlashcardWindow):
        FlashcardWindow.setObjectName("FlashcardWindow")
        FlashcardWindow.setFixedSize(796, 551)
        self.centralwidget = QtWidgets.QWidget(FlashcardWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(200, 120, 411, 271))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 269))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 431, 291))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.flashcard = QtWidgets.QLabel(self.frame)
        self.flashcard.setGeometry(QtCore.QRect(10, 0, 411, 271))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.flashcard.setFont(font)
        self.flashcard.setTextFormat(QtCore.Qt.AutoText)
        self.flashcard.setScaledContents(False)
        self.flashcard.setAlignment(QtCore.Qt.AlignCenter)
        self.flashcard.setObjectName("flashcard")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 0, 791, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.notesName = QtWidgets.QLabel(self.centralwidget)
        self.notesName.setGeometry(QtCore.QRect(0, 50, 791, 51))
        self.notesName.setStyleSheet("font: 36pt \".AppleSystemUIFont\";")
        self.notesName.setAlignment(QtCore.Qt.AlignCenter)
        self.notesName.setObjectName("notesName")
        self.nextPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextPushButton.setGeometry(QtCore.QRect(510, 410, 113, 32))
        self.nextPushButton.setObjectName("nextPushButton")
        self.rotationPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.rotationPushButton.setGeometry(QtCore.QRect(190, 410, 113, 32))
        self.rotationPushButton.setObjectName("rotationPushButton")
        FlashcardWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FlashcardWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 24))
        self.menubar.setObjectName("menubar")
        FlashcardWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FlashcardWindow)
        self.statusbar.setObjectName("statusbar")
        FlashcardWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FlashcardWindow)
        QtCore.QMetaObject.connectSlotsByName(FlashcardWindow)

    def retranslateUi(self, FlashcardWindow):
        _translate = QtCore.QCoreApplication.translate
        FlashcardWindow.setWindowTitle(_translate("FlashcardWindow", "Приложение для ведения конспектов и "
                                                                     "последующего автоматического перехода записей в"
                                                                     " карточки для заучивания материала"))
        self.flashcard.setText(_translate("FlashcardWindow", "Question\n"
""))
        self.notesName.setText(_translate("FlashcardWindow", "First"))
        self.nextPushButton.setText(_translate("FlashcardWindow", "Next"))
        self.rotationPushButton.setText(_translate("FlashcardWindow", "Rotation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FlashcardWindow = QtWidgets.QMainWindow()
    ui = Ui_FlashcardWindow()
    ui.setupUi(FlashcardWindow)
    FlashcardWindow.show()
    sys.exit(app.exec_())
