# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'noteWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NoteWindow(object):
    def setupUi(self, NoteWindow):
        NoteWindow.setObjectName("NoteWindow")
        NoteWindow.setFixedSize(800, 719)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NoteWindow.sizePolicy().hasHeightForWidth())
        NoteWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(NoteWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 90, 641, 381))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 639, 379))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.qaTable = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.qaTable.setGeometry(QtCore.QRect(10, 0, 611, 381))
        self.qaTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.qaTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.qaTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.qaTable.setShowGrid(True)
        self.qaTable.setGridStyle(QtCore.Qt.DashLine)
        self.qaTable.setWordWrap(False)
        self.qaTable.setCornerButtonEnabled(False)
        self.qaTable.setRowCount(20)
        self.qaTable.setColumnCount(2)
        self.qaTable.setObjectName("qaTable")
        item = QtWidgets.QTableWidgetItem()
        self.qaTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.qaTable.setHorizontalHeaderItem(1, item)
        self.qaTable.horizontalHeader().setVisible(True)
        self.qaTable.horizontalHeader().setCascadingSectionResizes(True)
        self.qaTable.horizontalHeader().setDefaultSectionSize(305)
        self.qaTable.horizontalHeader().setMinimumSectionSize(20)
        self.qaTable.horizontalHeader().setStretchLastSection(True)
        self.qaTable.verticalHeader().setVisible(False)
        self.qaTable.verticalHeader().setCascadingSectionResizes(True)
        self.qaTable.verticalHeader().setStretchLastSection(True)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(660, 593, 113, 32))
        self.saveButton.setObjectName("saveButton")
        self.additionalInfoTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.additionalInfoTextEdit.setGeometry(QtCore.QRect(30, 540, 601, 79))
        self.additionalInfoTextEdit.setObjectName("textEdit")
        self.additionalInfo = QtWidgets.QLabel(self.centralwidget)
        self.additionalInfo.setGeometry(QtCore.QRect(30, 490, 231, 31))
        self.additionalInfo.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.additionalInfo.setObjectName("additionalInfo")
        self.notesName = QtWidgets.QLabel(self.centralwidget)
        self.notesName.setGeometry(QtCore.QRect(30, 20, 601, 51))
        self.notesName.setStyleSheet("font: 36pt \".AppleSystemUIFont\";")
        self.notesName.setObjectName("notesName")
        self.startStudyPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startStudyPushButton.setGeometry(QtCore.QRect(660, 30, 113, 32))
        self.startStudyPushButton.setObjectName("startStudyPushButton")
        NoteWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NoteWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        NoteWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NoteWindow)
        self.statusbar.setObjectName("statusbar")
        NoteWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(NoteWindow)
        self.toolBar.setObjectName("toolBar")
        NoteWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(NoteWindow)
        QtCore.QMetaObject.connectSlotsByName(NoteWindow)

    def retranslateUi(self, NoteWindow):
        _translate = QtCore.QCoreApplication.translate
        NoteWindow.setWindowTitle(_translate("NoteWindow", "Приложение для ведения конспектов и последующего автоматического перехода записей в карточки для заучивания материала"))
        item = self.qaTable.horizontalHeaderItem(0)
        item.setText(_translate("NoteWindow", "Question"))
        item = self.qaTable.horizontalHeaderItem(1)
        item.setText(_translate("NoteWindow", "Answer"))
        self.saveButton.setText(_translate("NoteWindow", "Save note"))
        self.additionalInfo.setText(_translate("NoteWindow", "Additional Information"))
        self.notesName.setText(_translate("NoteWindow", "Note\'s Name"))
        self.startStudyPushButton.setText(_translate("NoteWindow", "Start study"))
        self.toolBar.setWindowTitle(_translate("NoteWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NoteWindow = QtWidgets.QMainWindow()
    ui = Ui_NoteWindow()
    ui.setupUi(NoteWindow)
    NoteWindow.show()
    sys.exit(app.exec_())
